# Site settings
title: J Rahel
email: "website@jrahel.nl"
description: "J Rahel photo gallery"
url: "https://jrahel.nl"
baseurl: "/"
facebook_username: ""
twitter_username: ""
instagram_username: ""
github_username:  ""
deviantart_username: ""
flickr_username: ""
discus_shortname: ""
share: true

# Owner/author information
owner:
  name: J Rahel
  avatar: avatar.png
  favicon: favicon.ico
  info: 

# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
#Set 'provider: false' to disable comments globally.
# Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
#
comments :
  provider : disqus
  disqus :
    short_name : ""

# Internal nav
nav:
  - Amsterdamse_Bos: "https://jrahel.nl/photos/amsterdamse-bos/"  
  - Keukenhof: "https://sunbliss.github.io/photos/keukenhof/"
  - Indonesia: "https://sunbliss.github.io/photos/indonesia/"
  - Other: "https://sunbliss.github.io/photos/misc/"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 4000


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/journal/page:num/"
permalink: "/journal/:title/"
categories_path: "/journal/category/"
tags_path: "/journal/tag/"
gems: 
 - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
